version: '3.7'
services:
  stack:
    container_name: stack
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        dev.stack.title: ""
        dev.stack.description: ""
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/.next'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    labels:
      dev.stack.title: ""
      dev.stack.description: ""
