version: '3.7'
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      labels:
        dev.app.title: ""
        dev.app.description: ""
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
      - '/usr/src/app/.next'
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
    labels:
      dev.app.title: ""
      dev.app.description: ""
